name: public-chat-CI

on:
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  APP_PORT: ${{ secrets.APP_PORT }}
  CONTAINER_NAME: public-chat

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: |
          docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_TOKEN }}

      - name: Build docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .

      - name: Docker push
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Docker logout
        run: |
          docker logout

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy container
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USER }}
          envs: REGISTRY,IMAGE_NAME,CONTAINER_NAME,APP_PORT
          script: |
            echo "Login to registry"
            docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_TOKEN
            
            echo "Pulling latest image"
            docker pull $REGISTRY/$IMAGE_NAME
            
            echo "Stopping container"
            docker stop $CONTAINER_NAME
            
            echo "Removing container"
            docker rm $CONTAINER_NAME
            
            echo "Run container"
            docker run -it -d --name $CONTAINER_NAME -p $APP_PORT:3000 $REGISTRY/$IMAGE_NAME
            
            docker logout
            
            echo "Done"
